### ISSUE TITLE
It is not possible to set a newline at tail of a block using new-line function

### ISSUE THREAD

**Issue by Oldes** [rebol/rebol-issues#2303]
This works:
```
>> b: [1 2] new-line next b true append b 3 b 
== [1 
2 3 
] 
```
But this does not works:
```
>> b: [1 2] new-line tail b true append b 3 b 
== [1 2 3]
```
Expected result is:
```
== [1 2
3]
```

PS: Red has same problem: https://github.com/red/red/issues/3348

**Comment by hostilefork** [comment]
The new line flag is a bit set on value cells.  We might say it indicates that a new line be output *before that value* (it actually means more than that regarding the overall molding process, in terms of the presence or absence, and how the brackets/parentheses etc. format).

Following the "output a new line before" concept with your example, you have two values in your block.  But you're trying to set a bit on a "third position".  That third position is at the tail, which you may think of as some "place" that is the same as any other.  But it isn't, because there's no "value" there (as far as the user is concerned).  The length is 2, you're talking about the "value at 3".

As it so happens, R3-Alpha did have a full "cell" at position 3, of the internal datatype END!.   It is much like a null terminator in strings in C.  You might think that, since it is there, you could put a newline flag on it.  If I recall correctly, the scanner would actually set the newline bit on those ends...they just weren't paid attention to by molding.

*(Ren-C eliminated END! and did a lot of cool things in the process, including being able to fit 1-element arrays into series nodes, terminated by single bit flags.  Separate topic.)*

But if you decide to use that END! cell as the place to put your intention for this "tail flag", it has a bit of trouble.  It's not really a user-exposed value, and it's not clear how when you append this new cell (the 3) you would expect the bracket on your end cell to migrate its bit onto this new last element.  More likely you would get:

    == [1 2 3
    ]
 
The reason the same behavior is in Red is because this model just works that way, and doesn't really fit what you are trying to do.  You want to pre-emptively set the flag for a value cell that "isn't there now, but will be coming later".  Yet the language doesn't model there as being anything at that position, nor does it really communicate how even if there were, properties you assigned to that non-existent position would be transferred to things that showed up at the tail later.

**Comment by Oldes** [comment]
Ok... I'm not going to change it... I ended using such a code in my script:
```
>> b: [1 2]  new-line b true  append b new-line [3] true  b
== [
    1 2
    3
]
```

**Comment by hostilefork** [comment]
> Ok... I'm not going to change it

Well, *I* decided to.  :-P

https://github.com/metaeducation/ren-c/pull/792

As I said, there had to be another bit.  With an array of length N, you have N + 1 positions *between* values.  I made a new array flag, ARRAY_FLAG_TAIL_NEWLINE.

Since the code for mutating arrays all goes through Modify_Array, there's a place to put the logic for moving the bits around between array cells and the array itself.  I kind of hacked it in there, but someday it can probably be done more elegantly.  The real question is about the mechanics of what you want.

So if you want:

    [
        1 2
        3
     ]

Your example would need to be:

    b: copy [1 2]
    new-line tail b
    append/line b 3

Or you wouldn't need the new-line on the tail of b if all your appends had been using append/line, so you could have said:

    b: copy []
    append/line b [1 2]
    append/line b 3

Or had you denoted that it had a new line at the tail in source:

    b: copy [a b
    ]
    append/line b 3

*(I've wondered if there should be a scanner clue to do this on one line, like `b: copy [a b ^/]`, but I don't know.)*

If you don't use the /LINE refinement it can still work, but with more manual effort:

    b: copy [1 2]
    new-line b true
    new-line tail b true
    append b 3
    new-line tail b true

APPEND/LINE assumes that if the array you are appending to doesn't have a new-line at the head, that's probably not what you want, so it puts one there.

Having the N + 1 spots is a bit more complex, but I think that the control is useful.
