### ISSUE TITLE
Rebol removes/converts CR character when doing binary to string conversion

### ISSUE THREAD

**Issue by Oldes** [rebol/rebol-issues#2336]
I consider this to be a wrong behaviour:
```
>> to-string probe to-binary probe to-string CR
"^M"
#{0D}
== "^/"
```
The result should be again `CR` (`"^M"`) like it is in Rebol2, Red and Ren-C

This is also wrong:
```
>> to-string probe to-binary probe to-string crlf
"^M^/"
#{0D0A}
== "^/"
```

**Comment by hostilefork** [comment]
*Silently converting CR to LF is clearly bad*.  But I think that blindly accepting the CR in a TO conversion may be bad too.  At least in my world, I'd rather see this being an error unless I somehow indicated I wanted to allow it.

One of the key differences between calling something a "string" vs. a "binary" is that it follows some rules besides being just bytes.  I think the system helping to enforce these rules is good.  If you don't want the rules and the safety and benefits they give, it would seem better to leave it as a binary.

As an example: if a binary has embedded `#{00}` bytes, I think you should have to do something about that before converting to a string.  If you don't, consider the effects on the API:

    REBVAL *some_string = rebRun("unspaced [<a> to string! binary </a>]");
    /* ... */
    char *cstr = rebSpell(some_string);

If that could have made a string with embedded '\0', your API that extracts spellings has to give back a length -or- it has to throw away data after the '\0'.  What "libRebol" does is makes a separate API called `rebBytes()` that gives back both a count and a pointer, and you can use it on either strings or binaries. 
 But you have a strong guarantee that an ANY-STRING! can always safely use the version that returns just a single NUL-terminated C string, and a BINARY! can't be passed to rebSpell().

It's a slippery slope to know exactly what parts of the system should be tolerant (**append string CR** feels fairly purposeful, and it is a "legal codepoint").  But still: I'd prefer an error by default, and have some relatively convenient way to use a codec that gives options on conversions or discarding.  If you get CRs leaking into your strings and all the `newline` oriented features don't work, you should know what you're getting into.

I think you really do need a codec, because there's so many variants of "bad forms" in CR => LF conversion, some of which should trigger warnings ("...CR....CR LF....LF CR...").

Anyway, this is still a fairly open issue in my book...and I see why there was perceived value in "protecting the user from CRs" with the original choice.

**Comment by Oldes** [comment]
Hm... just found that this is duplicate of https://github.com/rebol/rebol-issues/issues/1517
