### ISSUE TITLE
ADMIN: I would like to be able to add own tags into these issues

### ISSUE THREAD

**Issue by Oldes** [rebol/rebol-issues#2403]
What I can do to be able to add own tags and so be able to filter what I consider to be fixed/implemented?

**Comment by hostilefork** [comment]
I don't believe it is possible to give you tagging rights without giving you broader powers to close, edit, delete, etc. pretty much anything in the Issue DB.

If you would be willing to agree to *only* exercise tagging rights--with the understanding that the only issues you can edit and close are your own--I could lobby for you having that right.

I've followed this policy myself.  e.g. I mark things ren.resolved but do not close things that are not fixed in R3-Alpha that were opened by other people.  (If *I* originally opened the issue, and I no longer agree with the premise of my proposal, or have a better solution to what I answered with...I feel fine closing it.)

Should you agree to this policy, I see no reason why you shouldn't be allowed to manage tags for your purposes.

**Comment by Oldes** [comment]
With all my honest, you are the last person I would beg for rights to **exercice** something.

Look, I'm not 18 years old. Actually I'm _reboling_ over 18 years (sooner than you come from your Microsoft work). I have my own work to do, but I still care about Rebol as my secret weapon. And so instead of adding wishes and issues in my own repository, I was using this place, because if nothing more, I still have a non conflicting PR https://github.com/rebol/rebol/pull/251 . 

And I'm feeling quite uncomfort that although you can mark my own reported issues as resolved in your Ren-C, often without linked related commits, I have rights like some newbie. If submitting an issue is any right at all.

So if you are the only active member with rights.. you can keep them. If there is someone else, who will decide, that I'm sane enough not deleting you comments or I don't know what you can imagine, than good for me, else I will probably copy these issues (one day, because I'm currently too busy) somewhere else (as were initially copied from CureCode), where I will not be treated like your _student_ or whatever.

**Comment by hostilefork** [comment]
With such an attitude, you are not going to get much help from me.

I offered a spirit and terms of collaboration, and a policy for doing it.  If you're not interested in that, fine.

Look into importing the issues into GitLab: https://docs.gitlab.com/ee/user/project/settings/import_export.html

**Comment by Oldes** [comment]
From someone who is named _Hostile Fork_ I was not expecting other attitude. It is sad, that it really looks that you are the only one left who has rights, although taken from @rebolbot

**Comment by hostilefork** [comment]
You really have a very skewed idea about things.

I have been working in a way that attempts to facilitate other people's ideas about how to address issues.  I've not closed issues just because they are resolved to my satisfaction (unless, as I said, they were my issues to start with).  I've used tags of my own.

My proposal was a simple agreement that you use a similar method.  Which you used as an opportunity to double down on your desire to be adversarial, and complain that I had not gone into research and detail of how each and every issue had been resolved in Ren-C to my satisfaction.

I am not obligated to do so--and often resolution is not in a single commit, but a system of decisions I've made that you have no interest in understanding.  Whenever possible, I do explain those decisions -- **and I have answered any questions you've asked**.   (Another thing you have shown no appreciation for.)

[We're building great things.](https://2019.reb4.me/talks)  That you're going to be off playing in a corner by yourself is just the destiny you have chosen.  *It didn't have to be that way.*  You make it that way.

**Comment by gchiu** [comment]
Curecode is still running https://www.curecode.org/rebol3/view-tickets.rsp so Oldes is welcome to scrape his own version as the ren-c team did.  I think Johnk did that under my rebolbot account.

**Comment by Oldes** [comment]
And I just wanted to use own tags.

**Comment by hostilefork** [comment]
> And I just wanted to use own tags.

Then you should have said "okay, that sounds good" when I proposed how we go about that--instead of making every effort to suggest working with you was going to be a problem.

**Comment by Oldes** [comment]
Maybe you realized that I don't want to be working with you on your great things. I want to be working on my own things (which I need btw) and just wanted to have same opportunity as you have to tag my issues. It is you who is dealing like the only Rebol owner.

**Comment by Oldes** [comment]
And don't tell me, that you don't know, that I don't close my issues, which I consider to be resolved, either, so don't know, why should I touch yours.

**Comment by hostilefork** [comment]
>  It is you who is dealing like the only Rebol owner.

We very well could have imported this database into Ren-C and worked with it there, and not offered to try to do this collaboration as we are.  We didn't, and that earns no respect from you--just as the work done earns no respect.

You are the one throwing a tantrum, very expressly saying you *don't* want to collaborate, and expecting others to bend over backwards for that.  We won't.

I think it's time you scrape the data and go off to your own island, where you can have the dream you want--to be the only Rebol owner of your own Rebol.  Because really it's you who can't share or work with others.  Not Red, not us, not anyone.

Go.

**Comment by hostilefork** [comment]
I don't think you can import issue DBs into GitLab if you aren't in the organization.  So I have imported the issue database to a GitLab project as a copy, to be given to you to manage fully:

https://gitlab.com/hostilefork/rebol-issues/issues

Direct transfer to a user is not possible, so I've [created a group which you are an owner of](https://gitlab.com/oldes-transfer).  You may transfer the issue database out of that.  Or if I am wrong, I guess you can import it yourself--or scrape it some other way.  But this is at least one effort-free solution for you, and we need not talk again.

**Comment by hostilefork** [comment]
Please note that this is a **time-limited offer**.

If you take the database by Friday, then I will direct anyone interested in R3-Alpha to you as the official maintainer of that train of thought.  You can be the boss.  Go for it.

BUT...if you don't take the database by Friday, I will mark it private and keep it as a backup.  *(It's not clear that GitLab will let me import it more than once.  These days I prefer GitLab actually and am thinking of moving there...so this is me sticking my neck out for you for no reason, really.)*

["This deal is very fair, and I'm happy to be a part of it."](https://www.youtube.com/watch?v=WpE_xMRiCLE)

**Comment by hostilefork** [comment]
I hadn't refreshed my GitLab page, but it now appears that the issue DB has disappeared from the [Oldes Transfer](https://gitlab.com/oldes-transfer) group.

But I do not see it then showing up [in your account](https://gitlab.com/Oldes), which means you have either taken it privately or deleted it.  I honestly don't care which choice you made.

[John thinks this was the right call:](https://chat.stackoverflow.com/transcript/message/48565020#48565020):

> this seems like a good move. Oldes stated "I want to be working on my own things" so setting up a new clone of the issue db for him seems to be the ideal solution.

[Graham agrees that there wasn't a basis for giving you admin rights:](https://chat.stackoverflow.com/transcript/message/48563302#48563302)

> He wants full rights as a team member without being in the team. As is mentioned, curecode is still there and can be scraped as we did and imported.

I am serious, however, that if you make the database public I will direct anyone interested in R3-Alpha to you.  But as I see no public DB from you...it seems you are not interested in anyone else, so, I'm just going to assume you got what you wanted, and case closed.

**Comment by hostilefork** [comment]
Oh, turns out that GitLab logged me out, and so the repo disappeared.  You haven't done the transfer.

So read the original message.

**Comment by hostilefork** [comment]
Oldes chose to do his own API-based import, the resulting repository is:

https://github.com/Oldes/Rebol-issues
