### ISSUE TITLE
MOLD/LIMIT calculates size incorrectly (plus asserts with LIMIT <= 3)

### ISSUE THREAD

**Issue by giuliolunati** [rebol/rebol-issues#2405]
`system/options/dump-size: 3                       spaced [".." (t: 1 -- t)]`
=>
-- ../src/include/datatypes/sys-series.h:154:
SET_SERIES_USED: assertion "used < sizeof(s->content)" failed

(r3 version: 0.13.2 debug 3183acf3)

**Comment by hostilefork** [comment]
*(Sorry to delay in looking at this...had some travel, then working on other things with stackless...)*

**Note: The issue repositories are being merged.  When the project is renamed, what was formerly the rebol-issues (this database) will be the new project's issues, and all the ren-c issues will be migrated in.  I moved this issue as an example, but will eventually move them all...**

---

There were a couple of bugs here.  One is that the mold limit calculations were looking at the absolute length of the mold buffer instead of just the length of the part that was applicable to the current bit of the "mold stack".  The other issue is that the MOLD/LIMIT wasn't originally exposed via the native, so the system could be vetted for calls that passed in less than 3 characters of length--which wouldn't be enough even for a "..." to say it was truncated.

Red doesn't add in the "...", and just truncates the mold if you ask for a limit (they call it MOLD/PART):

    red>> mold/part "abcdefg" 3
    == {"ab}

There's something to be said for not including the "...".  Giving more characters than you asked for seems a little dicey, plus if you are writing a more complicated UI then you might want to make a button to expand a truncated mold.  It would be error prone and awkward to reverse-engineer such a button by hunting for the "..." on the tail.  But you also want to know if a truncation happened or not.

So how about you don't get back the "..." in a truncated mold, so it's exactly the limit of the size you ask for.  But you can also ask for a flag of whether a truncation happened or not.

     >> mold/limit/truncated "abcdefg" 3 'trunc
     == {"ab}

     >> trunc
     == #[true]

With multiple return values this could look like:

     >> [str trunc]: mold/limit "abcdefg" 3
     == {"ab}

     >> str
     == {"ab}

     >> trunc
     == #[true]

It's a little more work, but since it provides the information you could write a variant that makes it easier.  Something like:

     moldclip: func [value [any-value!] limit [integer!] <local> str trunc ] [
          if limit < 3 [fail "MOLDCLIP needs at least 3 chars for {...}"]        
          [str trunc]: mold/limit :value limit - 3
          return append str if trunc ["..."]
      ]

Anyway, this seems to take care of the crash:

https://github.com/metaeducation/ren-c/commit/bf78336e19516de53a8ae9d2170bfe6169d689a4

But there's a lot of work in stackless to be done on molding, so doing a better job of handling mold limits and recursions is going to be part of that.  [Explanation of the emerging Generator / Yielder!](https://forum.rebol.info/t/yielder-and-generator-and-thinking-about-coroutines/1311)
