### ISSUE TITLE
MAKE VARARGS! and evaluation

### ISSUE THREAD

**Issue by giuliolunati** [rebol/rebol-issues#2513]
When passing a varargs-from-block to a variadic function, I wish were respected args specifications about quoting/evaluating

**Comment by hostilefork** [comment]
Okay, now I remember why it works this way.

The reason is that usually, the rule for how the parameter is processed comes from the argument that was marked variadic.  But when you MAKE VARARGS! from a block, that kind of argument doesn't come from a parameter.

So what would this be?

    v: make varargs! [1 + 2]
    take v

Should that act quoted or should it evaluate?  There's no information to know.

Right now the rules are a little fuzzy.  How do you think it should work?  Should TAKE only be willing to operate on a varargs! that has been passed as a parameter, and then follow the quote style of that parameter?

Maybe you could write up some cases and expected behavior...
