### ISSUE TITLE
EQUAL-OR-LESSER? returning wrong result

### ISSUE THREAD

**Issue by BlackATTR** [rebol/rebol-issues#2519]
The expected behavior here is correct: 

>> equal-or-lesser? 3-Feb-2021 4-Feb-2021
== #[true]

The behavior in this example, however, is incorrect:

>> equal-or-lesser? 3-Feb-2021/16:09:02.786-5:00 4-Feb-2021
== #[false]

**Comment by hostilefork** [comment]
Problem here was pretty simple: it was comparing the time component before the date component.  So a later-date-with-an-earlier-time would be seen as "<" an earlier-date-with-a-later-time.  [Fixed.](https://github.com/metaeducation/ren-c/commit/88c30fe5a5c5e12f34441c3934c0dfae62fa8fe5)

But other things have changed.  When I was trying to integrate some date tests Brett had written, they declared this to be an illegal comparison.  So this is what we get now:

    >> equal-or-lesser? 3-Feb-2021/16:09:02.786-5:00 4-Feb-2021
    ** Script Error: cannot compare 3-Feb-2021/16:09:02.786-5:00 with 4-Feb-2021

The issue is that in general, we can't give trustworthy answers when there is a mismatch of specificity like this.

But so long as one way or another you get both to have a time + zone component you can compare.  Here's one way:

    >> date1: 3-Feb-2021/16:09:02.786-5:00
    >> date2: 4-Feb-2021

    >> date1.zone: default [0]
    == -5:00

    >> date2.zone: default [0]
    == 0

    >> date1
    == 3-Feb-2021/16:09:02.786-5:00

    >> date2
    == 4-Feb-2021/0:00+0:00

    >> equal-or-lesser? date1 date2
    == #[true]
